"""Pre-flight reviewer gate (design: catch problems, never create output).

One adversarial LLM pass over each packaged application. Checks the failure
classes that actually sink applications:
  - cover letter claims not grounded in the vetted bullet pool (fabrication)
  - wrong/missing company name, mismatched title, hallucinated requirements
  - contradictions with locked answers (start date, salary, location)
  - tailoring that leads with the wrong emphasis for this posting
Verdict is binary: pass -> status 'reviewed'; flag -> status 'flagged' with
concrete reasons written to review.md. No rewrites, no taste notes.

Run standalone over all packaged jobs:  .venv\\Scripts\\python -m pipeline.reviewer
"""

import json
import sys
from pathlib import Path

from pydantic import BaseModel

from . import db, llm

ROOT = Path(__file__).resolve().parent.parent
APPS = ROOT / "data" / "applications"


class ReviewVerdict(BaseModel):
    verdict: str            # "pass" | "flag"
    issues: list[str]       # blocking problems (empty when verdict is pass)
    notes: list[str]        # non-blocking observations, max 3


_SCHEMA_NOTE = """

Respond with ONLY a JSON object, no markdown fences, matching exactly:
{"verdict": "pass|flag", "issues": [<blocking problems>], "notes": [<max 3 minor observations>]}"""


FACTS = ROOT / "data" / "facts.md"


def _tailored_bullets(folder: Path):
    """Extract generated bullet text from the tailored resume docx, if present."""
    docx_path = folder / "resume_tailored.docx"
    if not docx_path.exists():
        return ""
    from docx import Document
    doc = Document(docx_path)
    return "\n".join(p.text for p in doc.paragraphs
                     if p.style is not None and p.style.name == "List Paragraph")


def review_package(folder: Path, row, profile, model=llm.DEFAULT_MODEL) -> ReviewVerdict:
    cover = (folder / "cover_letter.md").read_text(encoding="utf-8-sig")
    answers = (folder / "answers.json").read_text(encoding="utf-8-sig")
    facts = FACTS.read_text(encoding="utf-8-sig")
    resume_text = _tailored_bullets(folder)

    prompt = f"""You are the final pre-submission reviewer for a job application package.
Your job is CATCHING problems, not improving prose. The resume bullets and cover
letter were GENERATED by an LLM from the fact corpus below, so fabrication checking
is the core job. Flag only blocking issues:

1. HARD FABRICATION ONLY. Flag a claim only if it is a checkable falsehood:
   - invented or altered employers, job titles, dates, degrees, certifications
   - changed/inflated/rounded-up NUMBERS (metrics must match the corpus exactly)
   - a NAMED tool, language, framework, or methodology with zero corpus basis
   - anything on the corpus NEVER-claim list
   EXPLICITLY ALLOWED - do NOT flag any of these:
   - paraphrase, synonyms, and mirroring the posting's vocabulary for things the
     corpus substantively supports (corpus "API testing (Postman, SoapUI)" may be
     written as "REST/web-services test automation"; corpus "defect triage" may be
     written as "bug lifecycle management")
   - reasonable adjacency and inference (CI pipelines imply build/deploy familiarity;
     release sign-off implies stakeholder communication)
   - qualitative and soft-skill claims (leadership, collaboration, rigor)
   - generous-but-true framing of scope and seniority
   When unsure whether something is a paraphrase or a new fact, treat it as a
   paraphrase and put it in notes instead of issues.
2. WRONG TARGET: company name missing or wrong anywhere, title mismatch, or content
   referencing requirements the posting does not contain.
3. CONTRADICTIONS: anything conflicting with the hard constraints in the corpus
   (start date, sponsorship, salary, the NEVER-claim list).

Do NOT flag style, tone, length, emphasis choices, or missed opportunities - those
go in notes (max 3).

FACT CORPUS (the only permissible source of claims):
{facts}

JOB POSTING:
Title: {row['title']}
Company: {row['company']}
Description: {(row['description'] or '')[:3500]}

GENERATED RESUME BULLETS:
{resume_text[:3000] or '(none - persona resume sent as-is, pre-vetted by the human)'}

COVER LETTER:
{cover[:3000]}

ANSWERS FILE:
{answers[:1500]}"""

    verdict = llm.complete_json(prompt, ReviewVerdict, _SCHEMA_NOTE, model)
    (folder / "review.md").write_text(
        f"# Pre-flight review: {verdict.verdict.upper()}\n\n"
        + ("## Blocking issues\n" + "\n".join(f"- {i}" for i in verdict.issues) + "\n\n"
           if verdict.issues else "No blocking issues.\n\n")
        + ("## Notes\n" + "\n".join(f"- {n}" for n in verdict.notes) + "\n"
           if verdict.notes else ""),
        encoding="utf-8-sig")
    return verdict


def review_all(statuses=("packaged",)):
    profile = json.loads((ROOT / "data" / "profile.json").read_text(encoding="utf-8-sig"))
    conn = db.connect()
    placeholders = ",".join("?" * len(statuses))
    rows = conn.execute(f"SELECT * FROM jobs WHERE status IN ({placeholders})", statuses).fetchall()
    print(f"reviewing {len(rows)} packages")
    for row in rows:
        folders = list(APPS.glob(f"{row['id']}-*"))
        if not folders:
            print(f"  ! no folder for job {row['id']}")
            continue
        try:
            verdict = review_package(folders[0], row, profile)
        except Exception as exc:
            print(f"  ! {folders[0].name}: {exc}")
            continue
        status = "reviewed" if verdict.verdict == "pass" else "flagged"
        conn.execute("UPDATE jobs SET status=? WHERE id=?", (status, row["id"]))
        conn.commit()
        marker = "PASS" if status == "reviewed" else "FLAG"
        print(f"  [{marker}] {folders[0].name}")
        for issue in verdict.issues:
            print(f"         - {issue}")


if __name__ == "__main__":
    review_all(tuple(sys.argv[1:]) or ("packaged",))
